export type BranchFlags =
  | "--list"
  | "--all"
  | "--remotes"
  | "--show-current"
  | "--no-color"
  | "--no-column"
  | "--verbose"
  | "--quiet"
  | "--no-abbrev"
  | "--omit-empty"
  | "--ignore-case"
  | "--track"
  | "--no-track"
  | "--set-upstream"
  | "--create-reflog"
  | "--no-create-reflog"
  | "--recurse-submodules"
  | "--force"
  | "--move"
  | "-M"
  | "--copy"
  | "-C"
  | "--delete"
  | "-D"
  | "--unset-upstream"
  | "--edit-description";

export type BranchOptions = { flags?: BranchFlags[] };
