// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY

export * from "./changedFileCount"
export * from "./diff"
export * from "./diffCommits"
export * from "./diffFiles"
export * from "./diffHead"
export * from "./diffRange"
export * from "./diffStaged"
export * from "./diffStats"
export * from "./diffStatsCommits"
export * from "./diffStatsStaged"
export * from "./diffStatStagedSummary"
export * from "./diffStatSummary"
export * from "./diffWorkingTree"
export * from "./getChangedFiles"
export * from "./getStagedFiles"
export * from "./hasBinaryChanges"
export * from "./hasDiff"
export * from "./hasOnlyEOLChanges"
export * from "./hasOnlyWhitespaceChanges"
export * from "./hasStagedDiff"
export * from "./stagedFileCount"
